routes/web.php
<?php

use App\Http\Controllers\Backend\Order\OrderController;
use Illuminate\Support\Facades\Route;
use Maatwebsite\Excel\Facades\Excel;


Route::group(['middleware' => 'language'], function () {
    Route::group(['middleware' => 'auth'], function () {
        /* begin */
        Route::group(['middleware' => 'role:admin', 'prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/get/{user_type}', [\App\Http\Controllers\Backend\User\UserController::class, 'index'])->name('index');

            Route::get('/create/{user_type}', [\App\Http\Controllers\Backend\User\UserController::class, 'create'])->name('create');

            Route::post('/store', [\App\Http\Controllers\Backend\User\UserController::class, 'store'])->name('store');

            Route::get('/edit/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'edit'])->name('edit');

            Route::post('/update/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'update'])->name('update');

            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'destroy'])->name('delete');

            Route::post('/change/password/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'changePassword'])->name('change.password');

            Route::get('/info/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'show'])->name('show');
        });
################################################################    Orders ######################################################
        Route::group(['middleware' => 'role:admin', 'prefix' => 'orders', 'as' => 'orders.'], function () {
            Route::get('/all', [\App\Http\Controllers\Backend\Order\OrderController::class, 'index'])->name('index');

            Route::get('/create', [\App\Http\Controllers\Backend\Order\OrderController::class, 'create'])->name('create');

            Route::post('/store', [\App\Http\Controllers\Backend\Order\OrderController::class, 'store'])->name('store');
            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\Order\OrderController::class, 'destroy'])->name('delete');

            Route::get('/edit/{id}', [\App\Http\Controllers\Backend\Order\OrderController::class, 'edit'])->name('edit');

            Route::post('/update/{id}', [\App\Http\Controllers\Backend\Order\OrderController::class, 'update'])->name('update');

            Route::post('/order/export/excel', [OrderController::class,'generateExcel'])->name('generateExcel');

            Route::get('/order/item/delete/{id}', [OrderController::class,'destroyOrderItem'])->name('items.delete');
            Route::get('/order/info/{order_id}', [OrderController::class,'InfoOrder'])->name('info');
            //
        });

        #########################################################################################################################
        Route::group(['middleware' => 'role:admin', 'prefix' => 'categories', 'as' => 'categories.'], function () {
            Route::get('/all', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'index'])->name('index');

            Route::get('/create', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'create'])->name('create');

            Route::post('/store', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'store'])->name('store');
            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'destroy'])->name('delete');

            Route::get('/edit/{id}', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'edit'])->name('edit');

            Route::post('/update/{id}', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'update'])->name('update');
        });
        Route::group(['middleware' => 'role:admin', 'prefix' => 'brands', 'as' => 'brand.'], function () {
            Route::get('/all', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'index'])->name('index');

            Route::get('/create', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'create'])->name('create');

            Route::post('/store', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'store'])->name('store');
            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'destroy'])->name('delete');

            Route::get('/edit/{id}', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'edit'])->name('edit');

            Route::post('/update/{id}', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'update'])->name('update');
        });

        Route::group(['middleware' => 'role:admin', 'prefix' => 'product', 'as' => 'product.'], function () {
            Route::get('/all', [\App\Http\Controllers\Backend\Product\ProductController::class, 'index'])->name('index');
            Route::get('/create', [\App\Http\Controllers\Backend\Product\ProductController::class, 'create'])->name('create');
            Route::post('/store', [\App\Http\Controllers\Backend\Product\ProductController::class, 'store'])->name('store');
            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\Product\ProductController::class, 'destroy'])->name('delete');
        });

        Route::group(['middleware' => 'role:admin', 'prefix' => 'aboutApp', 'as' => 'aboutApp.'], function () {
            Route::get('/', [\App\Http\Controllers\Backend\AboutApp\AboutAppController::class, 'index'])->name('index');

            Route::get('/edit', [\App\Http\Controllers\Backend\AboutApp\AboutAppController::class, 'edit'])->name('edit');

            Route::post('/update', [\App\Http\Controllers\Backend\AboutApp\AboutAppController::class, 'update'])->name('update');
        });

        Route::group(['middleware' => 'role:admin', 'prefix' => 'privacyPolicy', 'as' => 'privacyPolicy.'], function () {
            Route::get('/', [\App\Http\Controllers\Backend\PrivacyPolicy\PrivacyPolicyController::class, 'index'])->name('index');

            Route::get('/edit', [\App\Http\Controllers\Backend\PrivacyPolicy\PrivacyPolicyController::class, 'edit'])->name('edit');

            Route::post('/update', [\App\Http\Controllers\Backend\PrivacyPolicy\PrivacyPolicyController::class, 'update'])->name('update');
        });

        Route::group(['middleware' => 'role:admin'], function () {
            Route::get('/', [\App\Http\Controllers\Backend\Dashboard\DashboardController::class, 'index'])->name('dashboard');

            Route::post('/switchLang', [\App\Http\Controllers\BaseController::class, 'changeLangWeb'])->name('app.change.lang');
        });

        Route::get('/logout', [\App\Http\Controllers\Backend\Auth\AuthController::class, 'logout'])->name('logout');




    });

    Route::group(['middleware' => 'guest'], function () {
        Route::get('/login', [\App\Http\Controllers\Backend\Auth\AuthController::class, 'showLoginForm'])->name('PageLogin');

        Route::post('login', [\App\Http\Controllers\Backend\Auth\AuthController::class, 'login'])->name('login');

        if (!auth()) {
            Route::get('{any}', function () {
                return redirect(\route('PageLogin'));
            })->where('any', '.*');
        }
    });
});

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\BaseController;
use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderItems;
use App\Traits\GeneralFunction;
use Illuminate\Http\Request;

class OrderController extends BaseController
{
    use GeneralFunction;

    public function __construct(Request $request)
    {


        $this->changeLang(\request('lang'));

    }
    public function getFullInformation()
    {
        $order = Order::getUserOrder(\request()->user()->id);
        return $this->sendResponseWithoutMessage($order);
    }

    public function addItemToOrder(Request $request)
    {
        $rules = [
            'product_id' => 'required|exists:products,id',
        ];
        $vr = $this->validateRequest($request, $rules);
        if ($vr['status'] === false) {
            return $this->sendErrors($vr['errors'], 400);
        }
        $order = Order::getUserOrder(\request()->user()->id);
        OrderItems::addToOrder(["order_id"=>$order->id,"product_id"=>$request->product_id]);
        return $this->sendResponseWithoutMessage($order);
    }


    public function removeItemFromOrderOrder(Request $request)
    {
        $rules = [
            'item_id' => 'required|exists:order_items,id',
        ];
        $vr = $this->validateRequest($request, $rules);
        if ($vr['status'] === false) {
            return $this->sendErrors($vr['errors'], 400);
        }

        OrderItems::delfromOrder($request->item_id );
        $order = Order::getUserOrder(\request()->user()->id);
        return $this->sendResponseWithoutMessage($order);
    }

    public function checkOut()
    {
        $order = Order::getUserOrder(\request()->user()->id);
        if(count($order->items)){
        $res = Order::doneOrder($order);
        return $this->sendResponseWithoutMessage($res);
        }
        else {
            return $this->sendError(__("Your Order Is Empty"),400);
        }


    }


    public function getMyOrders()
    {
        $orders = Order::where(
            [
                ['client_id','=',\request()->user()->id],
                ['status','=',"done"]

            ])->get();
        return $this->sendResponseWithoutMessage($orders);
    }


    public function getOrders($status)
    {
        if(auth()->user()->user_type != "admin")  return $this->sendError(__("forbidden "),403);

        $orders = Order::where(
            [

                ['status','=',$status]

            ])->get();
        return $this->sendResponseWithoutMessage($orders->load('owner'));
    }
}

app/Http/Controllers/Backend/AboutApp/AboutAppController.php
<?php

namespace App\Http\Controllers\Backend\AboutApp;

use App\Http\Controllers\BaseController;
use App\Models\About\AboutApp;
use App\Models\Ads\AdsManagement;
use Illuminate\Http\Request;

class AboutAppController extends BaseController
{

    public function index()
    {
        try {
            $about_en = AboutApp::query()->where('lang', 'en')->first();
            $about_ar = AboutApp::query()->where('lang', 'ar')->first();
            return view('backend.AboutApp.index', compact('about_en', 'about_ar'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    public function create()
    {

    }

    public function store(Request $request)
    {

    }

    public function show($id)
    {

    }

    public function edit()
    {
        try {
            $about_en = AboutApp::query()->where('lang', 'en')->first();
            $about_ar = AboutApp::query()->where('lang', 'ar')->first();
            return \view('backend.AboutApp.edit', compact('about_en', 'about_ar'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    public function update(Request $request)
    {
        try {

            $rules = [
                'information_ar' => 'required',
                'information_en' => 'required',
            ];
            $res_validate = $this->checkRequest($request, $rules);
            if (!$res_validate['status']) return redirect()->back()->withErrors($res_validate['messages']);

            $about_en = AboutApp::query()->where('lang', 'en')->first();
            $about_ar = AboutApp::query()->where('lang', 'ar')->first();

            if ($request->email != null) {
                $about_en->email = $request->email;
                $about_ar->email = $request->email;
            }
            if ($request->hasFile('logo')) {
                $about_en->logo = $this->uploadAppLogo($request->logo);
                $about_ar->logo = $about_en->logo;
            }
            $about_en->information = $request->information_en;
            $about_ar->information = $request->information_ar;

            $about_en->save();
            $about_ar->save();

            return redirect(route('aboutApp.index'))->withStatus(__('custom_messages.general_messages.crud.updated'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    public
    function destroy($id)
    {

    }
}

app/Http/Controllers/Backend/Brand/BrandController.php
<?php

namespace App\Http\Controllers\Backend\Brand;

use App\Http\Controllers\BaseController;
use App\Http\Controllers\Controller;
use App\Models\Brand;
use App\Models\Category;
use Illuminate\Http\Request;

class BrandController extends BaseController
{


    public function index()
    {
        try {
            $data = Brand::query()->where('is_deleted', 0)->get();
            return view('backend.brand.index', compact('data'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            return view('backend.brand.create');
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $rules = [
                'name_en' => 'required|string|max:191',
                'name_ar' => 'required|string|max:191',
            ];
            $res_validate = $this->checkRequest($request, $rules);
            if (!$res_validate['status']) return redirect()->back()->withErrors($res_validate['messages']);
            $data = $request->only([
                'name_en',
                'name_ar',
            ]);
            if (!is_null($request->image)) {
                $data['media_path'] = $this->uploadCategoryPhoto($request);
            }

            $brand = Brand::query()->create($data);

            return  redirect()->route('brand.index')

                ->withStatus(ucfirst(__('custom_messages.general_messages.crud.created')));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        try {
            $data = Brand::query()->find($id);
            return view('backend.brand.edit', compact('data'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $brand_id = $id;
            $brand = Brand::query()->find($brand_id);
            $rules = [
                'name_en' => 'required|string|max:191',
                'name_ar' => 'required|string|max:191',
            ];
            $res_validate = $this->checkRequest($request, $rules);
            if (!$res_validate['status']) return redirect()->back()->withErrors($res_validate['messages']);
            $brand->name_en = $request->name_en;
            $brand->name_ar = $request->name_ar;
            if (!is_null($request->image)) {
                $brand->media_path = $this->uploadCategoryPhoto($request);
            }

            $brand->save();


            return redirect(route('brand.index'))
                ->withStatus(__('custom_messages.general_messages.crud.updated'));

        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $brand = Brand::query()->find($id);
            $brand->update([
                'is_deleted'=>1
            ]);
            return  redirect()->back()->withStatus(__('custom_messages.general_messages.crud.deleted'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }


}

resources/views/backend/orders/index.blade.php
 @extends('master_layouts.app')

@section('content_head')
    @include('master_layouts.includes.menu_content_head',['title_page'=>__('dashboard.orders.management')])
@endsection
@section('content')

    <div class="">
        @include('includes.errors')
    </div>
    <div class="">
        @include('includes.success')
    </div>

    <div class="col-12">
        <div class="card-header" style="">
            <div class="card-toolbar row">
                <a href="{{route('dashboard')}}" class="btn btn-light-primary font-weight-bolder mr-2">
                    <i class="flaticon2-back icon-sm"></i>{{__('dashboard.back')}}</a>
                <div class="btn-group">

                    <a href="{{route('orders.create')}} "
                       class="btn btn-primary font-weight-bolder font-weight-lighter">
                        <i class="flaticon2-add-1 icon-sm"></i>{{__('dashboard.orders.create')}}
                    </a>
                    <form class=" mx-2" action="{{ route("orders.generateExcel") }}" method="post">
                        @csrf
                        <button type="submit"
                       class="btn btn-primary font-weight-bolder font-weight-lighter">
                        <i class="flaticon2-file-1 icon-sm"></i>{{__('dashboard.orders.generate_excel')}}
                    </button>
                    </form>


                </div>
            </div>
        </div>

        <div class="kt-portlet">
            <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
                <div class="kt-portlet__body kt-portlet__body--fit ">
                    <div class="  row">
                        <div class="col-md-12 col-sm-12 mt-5 ">
                            <div id="kt_subheader_search">
                                <form id="kt_subheader_search_form">
                                    <div class="kt-input-icon kt-input-icon--left kt-subheader__search">
                                        <input type="text" class="form-control" placeholder="Search..."
                                               id="generalSearch">
                                        <span class="kt-input-icon__icon kt-input-icon__icon--left">
													<span>
														<svg xmlns="http://www.w3.org/2000/svg"
                                                             xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                                                             height="24px" viewBox="0 0 24 24" version="1.1"
                                                             class="kt-svg-icon">
															<g stroke="none" stroke-width="1" fill="none"
                                                               fill-rule="evenodd">
																<rect x="0" y="0" width="24" height="24"></rect>
																<path
                                                                    d="M14.2928932,16.7071068 C13.9023689,16.3165825 13.9023689,15.6834175 14.2928932,15.2928932 C14.6834175,14.9023689 15.3165825,14.9023689 15.7071068,15.2928932 L19.7071068,19.2928932 C20.0976311,19.6834175 20.0976311,20.3165825 19.7071068,20.7071068 C19.3165825,21.0976311 18.6834175,21.0976311 18.2928932,20.7071068 L14.2928932,16.7071068 Z"
                                                                    fill="#000000" fill-rule="nonzero"
                                                                    opacity="0.3"></path>
																<path
                                                                    d="M11,16 C13.7614237,16 16,13.7614237 16,11 C16,8.23857625 13.7614237,6 11,6 C8.23857625,6 6,8.23857625 6,11 C6,13.7614237 8.23857625,16 11,16 Z M11,18 C7.13400675,18 4,14.8659932 4,11 C4,7.13400675 7.13400675,4 11,4 C14.8659932,4 18,7.13400675 18,11 C18,14.8659932 14.8659932,18 11,18 Z"
                                                                    fill="#000000" fill-rule="nonzero"></path>
															</g>
														</svg>

													</span>
												</span>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
                        <div class="kt-portlet__body kt-portlet__body--fit">

                            <table class="kt-datatable table-hover" id="kt-datatable" width="100%">
                                <thead>
                                <tr>
                                    <th>{{__('dashboard.orders.client_name')}}</th>
                                    <th>{{__('dashboard.orders.number')}}</th>
                                    <th>{{__('dashboard.orders.created_at')}}</th>
                                    <th>{{__('dashboard.orders.total')}}</th>
                                    <th>{{__('dashboard.controls')}}</th>
                                </tr>
                                </thead>
                                <tbody>

                                    @foreach($data as $datum)
                                        <tr>
                                            <td><b>{{ $datum->order_number }}</b></td>

                                            <td style="text-align: center !important;">
                                                <div class="kt-user-card-v2 overflow-hidden">
                                                    <div class="kt-user-card-v2__details">
                                                        <a class="kt-user-card-v2__name" href="#">

                                                                {{$datum->owner->name}}


                                                        </a>
                                                    </div>
                                                </div>
                                            </td>



                                            <td><b>{{ $datum->updated_at }}</b></td>

                                            <td><b>{{ $datum->final_total }}</b></td>



                                            {{--                                        controls--}}
                                            <td style="text-align: center !important;">
                                                <div class="dropdown ">
                                                    <a href="javascript:;" class="btn btn-sm btn-clean btn-icon btn-icon-md"
                                                       data-toggle="dropdown">
                                                        <i class="flaticon-more-1"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-right">
                                                        <ul class="kt-nav">

                                                            <li class="kt-nav__item">
                                                                <a class=" kt-nav__link" style="cursor: pointer "
                                                                   href="{{route('orders.info',$datum->id)}}"
                                                                   title="Edit">

                                                                    <i class="kt-nav__link-icon flaticon-edit"></i>
                                                                    <span
                                                                        class="kt-nav__link-text">{{__('dashboard.edit')}}</span>
                                                                </a>
                                                            </li>
                                                             <li class="kt-nav__item">
                                                                <a id="delete_user" class=" kt-nav__link"
                                                                   style="cursor: pointer "
                                                                   href="{{route('orders.delete',$datum->id)}}"
                                                                   title="Edit ">
                                                                    <i class=" kt-nav__link-icon flaticon-delete"></i>
                                                                    <span
                                                                        class="kt-nav__link-text">{{__('dashboard.delete')}}</span>
                                                                </a>
                                                            </li>

                                                        </ul>
                                                    </div>
                                                </div>
                                            </td>

                                        </tr>

                                    @endforeach

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>

            @endsection
            @section('js')
                <script src="{{asset('wjez/js/user_table.js')}}"></script>

@endsection