routes/web.php
<?php

use App\Http\Controllers\Backend\Order\OrderController;
use Illuminate\Support\Facades\Route;
use Maatwebsite\Excel\Facades\Excel;


Route::group(['middleware' => 'language'], function () {
    Route::group(['middleware' => 'auth'], function () {
        /* begin */
        Route::group(['middleware' => 'role:admin', 'prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/get/{user_type}', [\App\Http\Controllers\Backend\User\UserController::class, 'index'])->name('index');

            Route::get('/create/{user_type}', [\App\Http\Controllers\Backend\User\UserController::class, 'create'])->name('create');

            Route::post('/store', [\App\Http\Controllers\Backend\User\UserController::class, 'store'])->name('store');

            Route::get('/edit/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'edit'])->name('edit');

            Route::post('/update/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'update'])->name('update');

            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'destroy'])->name('delete');

            Route::post('/change/password/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'changePassword'])->name('change.password');

            Route::get('/info/{id}', [\App\Http\Controllers\Backend\User\UserController::class, 'show'])->name('show');
        });
################################################################    Orders ######################################################
        Route::group(['middleware' => 'role:admin', 'prefix' => 'orders', 'as' => 'orders.'], function () {
            Route::get('/all', [\App\Http\Controllers\Backend\Order\OrderController::class, 'index'])->name('index');

            Route::get('/create', [\App\Http\Controllers\Backend\Order\OrderController::class, 'create'])->name('create');

            Route::post('/store', [\App\Http\Controllers\Backend\Order\OrderController::class, 'store'])->name('store');
            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\Order\OrderController::class, 'destroy'])->name('delete');

            Route::get('/edit/{id}', [\App\Http\Controllers\Backend\Order\OrderController::class, 'edit'])->name('edit');

            Route::post('/update/{id}', [\App\Http\Controllers\Backend\Order\OrderController::class, 'update'])->name('update');

            Route::post('/order/export/excel', [OrderController::class,'generateExcel'])->name('generateExcel');

            Route::get('/order/item/delete/{id}', [OrderController::class,'destroyOrderItem'])->name('items.delete');
            Route::get('/order/info/{order_id}', [OrderController::class,'InfoOrder'])->name('info');
            //
        });

        #########################################################################################################################
        Route::group(['middleware' => 'role:admin', 'prefix' => 'categories', 'as' => 'categories.'], function () {
            Route::get('/all', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'index'])->name('index');

            Route::get('/create', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'create'])->name('create');

            Route::post('/store', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'store'])->name('store');
            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'destroy'])->name('delete');

            Route::get('/edit/{id}', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'edit'])->name('edit');

            Route::post('/update/{id}', [\App\Http\Controllers\Backend\Category\CategoryController::class, 'update'])->name('update');
        });
        Route::group(['middleware' => 'role:admin', 'prefix' => 'brands', 'as' => 'brand.'], function () {
            Route::get('/all', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'index'])->name('index');

            Route::get('/create', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'create'])->name('create');

            Route::post('/store', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'store'])->name('store');
            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'destroy'])->name('delete');

            Route::get('/edit/{id}', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'edit'])->name('edit');

            Route::post('/update/{id}', [\App\Http\Controllers\Backend\Brand\BrandController::class, 'update'])->name('update');
        });

        Route::group(['middleware' => 'role:admin', 'prefix' => 'product', 'as' => 'product.'], function () {
            Route::get('/all', [\App\Http\Controllers\Backend\Product\ProductController::class, 'index'])->name('index');
            Route::get('/create', [\App\Http\Controllers\Backend\Product\ProductController::class, 'create'])->name('create');
            Route::post('/store', [\App\Http\Controllers\Backend\Product\ProductController::class, 'store'])->name('store');
            Route::get('/delete/{id}', [\App\Http\Controllers\Backend\Product\ProductController::class, 'destroy'])->name('delete');
        });

        Route::group(['middleware' => 'role:admin', 'prefix' => 'aboutApp', 'as' => 'aboutApp.'], function () {
            Route::get('/', [\App\Http\Controllers\Backend\AboutApp\AboutAppController::class, 'index'])->name('index');

            Route::get('/edit', [\App\Http\Controllers\Backend\AboutApp\AboutAppController::class, 'edit'])->name('edit');

            Route::post('/update', [\App\Http\Controllers\Backend\AboutApp\AboutAppController::class, 'update'])->name('update');
        });

        Route::group(['middleware' => 'role:admin', 'prefix' => 'privacyPolicy', 'as' => 'privacyPolicy.'], function () {
            Route::get('/', [\App\Http\Controllers\Backend\PrivacyPolicy\PrivacyPolicyController::class, 'index'])->name('index');

            Route::get('/edit', [\App\Http\Controllers\Backend\PrivacyPolicy\PrivacyPolicyController::class, 'edit'])->name('edit');

            Route::post('/update', [\App\Http\Controllers\Backend\PrivacyPolicy\PrivacyPolicyController::class, 'update'])->name('update');
        });

        Route::group(['middleware' => 'role:admin'], function () {
            Route::get('/', [\App\Http\Controllers\Backend\Dashboard\DashboardController::class, 'index'])->name('dashboard');

            Route::post('/switchLang', [\App\Http\Controllers\BaseController::class, 'changeLangWeb'])->name('app.change.lang');
        });

        Route::get('/logout', [\App\Http\Controllers\Backend\Auth\AuthController::class, 'logout'])->name('logout');




    });

    Route::group(['middleware' => 'guest'], function () {
        Route::get('/login', [\App\Http\Controllers\Backend\Auth\AuthController::class, 'showLoginForm'])->name('PageLogin');

        Route::post('login', [\App\Http\Controllers\Backend\Auth\AuthController::class, 'login'])->name('login');

        if (!auth()) {
            Route::get('{any}', function () {
                return redirect(\route('PageLogin'));
            })->where('any', '.*');
        }
    });
});

app/Models/PrivacyPolicy/PrivacyPolicy.php
<?php

namespace App\Models\PrivacyPolicy;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PrivacyPolicy extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'description',
        'is_deleted',
    ];
}

app/Http/Controllers/Backend/AboutApp/AboutAppController.php
<?php

namespace App\Http\Controllers\Backend\AboutApp;

use App\Http\Controllers\BaseController;
use App\Models\About\AboutApp;
use App\Models\Ads\AdsManagement;
use Illuminate\Http\Request;

class AboutAppController extends BaseController
{

    public function index()
    {
        try {
            $about_en = AboutApp::query()->where('lang', 'en')->first();
            $about_ar = AboutApp::query()->where('lang', 'ar')->first();
            return view('backend.AboutApp.index', compact('about_en', 'about_ar'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    public function create()
    {

    }

    public function store(Request $request)
    {

    }

    public function show($id)
    {

    }

    public function edit()
    {
        try {
            $about_en = AboutApp::query()->where('lang', 'en')->first();
            $about_ar = AboutApp::query()->where('lang', 'ar')->first();
            return \view('backend.AboutApp.edit', compact('about_en', 'about_ar'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    public function update(Request $request)
    {
        try {

            $rules = [
                'information_ar' => 'required',
                'information_en' => 'required',
            ];
            $res_validate = $this->checkRequest($request, $rules);
            if (!$res_validate['status']) return redirect()->back()->withErrors($res_validate['messages']);

            $about_en = AboutApp::query()->where('lang', 'en')->first();
            $about_ar = AboutApp::query()->where('lang', 'ar')->first();

            if ($request->email != null) {
                $about_en->email = $request->email;
                $about_ar->email = $request->email;
            }
            if ($request->hasFile('logo')) {
                $about_en->logo = $this->uploadAppLogo($request->logo);
                $about_ar->logo = $about_en->logo;
            }
            $about_en->information = $request->information_en;
            $about_ar->information = $request->information_ar;

            $about_en->save();
            $about_ar->save();

            return redirect(route('aboutApp.index'))->withStatus(__('custom_messages.general_messages.crud.updated'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    public
    function destroy($id)
    {

    }
}

app/Http/Controllers/Backend/Brand/BrandController.php
<?php

namespace App\Http\Controllers\Backend\Brand;

use App\Http\Controllers\BaseController;
use App\Http\Controllers\Controller;
use App\Models\Brand;
use App\Models\Category;
use Illuminate\Http\Request;

class BrandController extends BaseController
{


    public function index()
    {
        try {
            $data = Brand::query()->where('is_deleted', 0)->get();
            return view('backend.brand.index', compact('data'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            return view('backend.brand.create');
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $rules = [
                'name_en' => 'required|string|max:191',
                'name_ar' => 'required|string|max:191',
            ];
            $res_validate = $this->checkRequest($request, $rules);
            if (!$res_validate['status']) return redirect()->back()->withErrors($res_validate['messages']);
            $data = $request->only([
                'name_en',
                'name_ar',
            ]);
            if (!is_null($request->image)) {
                $data['media_path'] = $this->uploadCategoryPhoto($request);
            }

            $brand = Brand::query()->create($data);

            return  redirect()->route('brand.index')

                ->withStatus(ucfirst(__('custom_messages.general_messages.crud.created')));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        try {
            $data = Brand::query()->find($id);
            return view('backend.brand.edit', compact('data'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $brand_id = $id;
            $brand = Brand::query()->find($brand_id);
            $rules = [
                'name_en' => 'required|string|max:191',
                'name_ar' => 'required|string|max:191',
            ];
            $res_validate = $this->checkRequest($request, $rules);
            if (!$res_validate['status']) return redirect()->back()->withErrors($res_validate['messages']);
            $brand->name_en = $request->name_en;
            $brand->name_ar = $request->name_ar;
            if (!is_null($request->image)) {
                $brand->media_path = $this->uploadCategoryPhoto($request);
            }

            $brand->save();


            return redirect(route('brand.index'))
                ->withStatus(__('custom_messages.general_messages.crud.updated'));

        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $brand = Brand::query()->find($id);
            $brand->update([
                'is_deleted'=>1
            ]);
            return  redirect()->back()->withStatus(__('custom_messages.general_messages.crud.deleted'));
        } catch (\Exception $ex) {
            return redirect()->back()->withErrors($ex->getMessage());
        }
    }


}

app/Http/Controllers/Backend/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Backend\Dashboard;

use App\Http\Controllers\BaseController;
use App\Http\Controllers\Controller;
use App\Models\Services\ServiceRequest;
use Illuminate\Http\Request;

class DashboardController extends BaseController
{

    public function index()
    {







        return view('backend.dashboard' );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/PrivacyPolicy/edit.blade.php
@extends('master_layouts.app')

@section('content_head')
    @include('master_layouts.includes.menu_content_head',['title_page'=>__('title_page.privacy_policy')])
@endsection

@section('content')
    <div class="">
        @include('includes.errors')
    </div>
    <div class="">
        @include('includes.success')
    </div>

    <div class="kt-portlet">
        <h3 class="kt-portlet__body">
            <form action="{{route('privacyPolicy.update')}}" method="post">
                @csrf
                <h3 style="text-align: center;color: #000000;">{{__('dashboard.english')}}</h3>
                <div class="kt-tinymce">
                    <textarea id="privacy_policy_en" name="description_en" class="tox-target">
                        {{$p_en->description}}
                    </textarea>
                </div>
                <h3 style="text-align: center;color: #000000;">{{__('dashboard.arabic')}}</h3>
                <div class="kt-tinymce">
                    <textarea id="privacy_policy_ar" name="description_ar" class="tox-target">
                        {{$p_ar->description}}
                    </textarea>
                </div>

                <div class="kt-form__actions">
                    <div class="row">
                        <div class="col-2"></div>
                        <div class="col-8 d-flex justify-content-center">
                            <button type="submit"
                                    class="btn btn-label-brand btn-bold font-weight-bold ">
                                <i class="ki ki-check icon-sm"></i>{{__('dashboard.save_change')}}
                            </button>
                            <a href="{{route('privacyPolicy.index')}}"
                               class="btn btn-clean btn-bold">{{__('dashboard.cancel')}}</a>
                        </div>
                        <div class="col-2"></div>
                    </div>
                </div>

            </form>
        </div>


    </div>
@endsection

@section('js')
    <script src="{{asset('assets/plugins/custom/tinymce/tinymce.bundle.js')}}" type="text/javascript"></script>
    <script !src>
        "use strict";
        $(document).ready(function () {
            tinymce.init({
                selector: 'textarea#privacy_policy_en',
                height: '100%',
                menubar: false,

                plugins: [
                    'advlist autolink lists link image charmap print preview anchor print preview ',
                    'searchreplace visualblocks code fullscreen',
                    'insertdatetime media table paste code help wordcount',

                ],
                toolbar: 'undo redo | formatselect | ' +
                    'bold italic backcolor | alignleft aligncenter ' +
                    'alignright alignjustify | bullist numlist outdent indent | ' +
                    'removeformat ' + 'anchor print preview',
                content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
            });
            tinymce.init({
                selector: 'textarea#privacy_policy_ar',
                height: '100%',
                menubar: false,

                plugins: [
                    'advlist autolink lists link image charmap print preview anchor print preview ',
                    'searchreplace visualblocks code fullscreen',
                    'insertdatetime media table paste code help wordcount',

                ],
                toolbar: 'undo redo | formatselect | ' +
                    'bold italic backcolor | alignleft aligncenter ' +
                    'alignright alignjustify | bullist numlist outdent indent | ' +
                    'removeformat ' + 'anchor print preview',
                content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
            });
        });
    </script>
@endsection

resources/views/backend/PrivacyPolicy/index.blade.php
@extends('master_layouts.app')

@section('content_head')
    @include('master_layouts.includes.menu_content_head',['title_page'=>__('title_page.privacy_policy')])
@endsection

@section('content')
    <div class="">
        @include('includes.errors')
    </div>
    <div class="">
        @include('includes.success')
    </div>
    <div class="card-header" style="">
        <div class="card-toolbar row">
            <div class="col-2"></div>
            <div class="col-8 d-flex justify-content-center">
                <a href="{{route('privacyPolicy.edit')}}" class="btn btn-label-brand btn-bold font-weight-bold ">
                    <i class="flaticon2-edit icon-sm"></i>{{__('dashboard.edit')}}
                </a>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
    <div class="kt-portlet">
        <div class="kt-portlet__body">
            <div class="kt-tinymce">
                @if(\Illuminate\Support\Facades\Session::get('locale') == 'en')
                    {!! $p_en->description !!}
                @endif
                @if(\Illuminate\Support\Facades\Session::get('locale') == 'ar')
                    {!! $p_ar->description !!}
                @endif
            </div>
        </div>
    </div>

    </div>
@endsection

@section('js')
    <script src="{{asset('assets/plugins/custom/tinymce/tinymce.bundle.js')}}" type="text/javascript"></script>
@endsection